<?php
$key = "rzp_live_KPZCC6rRwX0XV4";


include('api.php');
include('check-login.php');
$base_url = $_SESSION['base_url'];

$coupan = $_POST['coupan'];

$url_fetch = "buy-now";
$url = $base_url.$url_fetch;

$fields = array('coupan'=>$coupan,
'item_price'=>$_POST['original_price'],
'final_price'=>$_POST['final_price'],
'userid'=>$_POST['userid'],
'cart_id'=>$_POST['cartid'],
'course_id'=>$_POST['course_id'],
);

$data=api_call_auth("POST",$url, $fields, $_SESSION['token']);
// print_r($data);
if($data['status']=="success"){
    $purchase_id = $data['purchase_id'];
    // $transaction_id = rand(1,99999999);
//     $url_fetch = "update-purchase-status";
//     $url = $base_url.$url_fetch;
//     $field = array('purchase_id'=>$purchase_id,
//     'transaction_id'=>$transaction_id,
//     );
//     $data1=api_call_auth("POST",$url, $field, $_SESSION['token']);
// print_r($data1);

    
//         // echo $_SERVER['newprice'];
// //    print_r($data);
//     }
//     else{
//         echo "error";
        

    }



?>
<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_live_KPZCC6rRwX0XV4" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount= "<?php echo $_POST['final_price']*100; ?>"// Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $purchase_id ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with WorldsQNA"
    data-name="WQ DigiPay"
    data-description="WorldsQNA Online Learning Platform for all"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name=""
    data-prefill.email=""
    data-theme.color="#16C304"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>



